/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bluebox_levilamina_engine_Log */

#ifndef _Included_bluebox_levilamina_engine_Log
#define _Included_bluebox_levilamina_engine_Log
namespace lje{
/*
 * Class:     bluebox_levilamina_engine_Log
 * Method:    init
 * Signature: ()V
 */
void Java_bluebox_levilamina_engine_Log_init
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_levilamina_engine_Log
 * Method:    info
 * Signature: (Ljava/lang/String;)V
 */
void Java_bluebox_levilamina_engine_Log_info
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bluebox_levilamina_engine_Log
 * Method:    error
 * Signature: (Ljava/lang/String;)V
 */
void Java_bluebox_levilamina_engine_Log_error
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bluebox_levilamina_engine_Log
 * Method:    debug
 * Signature: (Ljava/lang/String;)V
 */
void Java_bluebox_levilamina_engine_Log_debug
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bluebox_levilamina_engine_Log
 * Method:    warn
 * Signature: (Ljava/lang/String;)V
 */
void Java_bluebox_levilamina_engine_Log_warn
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bluebox_levilamina_engine_Log
 * Method:    dispose
 * Signature: ()V
 */
void Java_bluebox_levilamina_engine_Log_dispose
  (JNIEnv *, jobject);

} // namespace lje

#endif
