#pragma once

/* DO NOT EDIT THIS FILE - it is machine generated */
#include "mc/world/actor/player/Player.h"
#include "mod/Entry.h"
#include <jni.h>

#define JCLASS_PLAYER PACK_JAVA_NAME("entity/Player")


namespace lje::j_Player{

jobject newJavaPlayer(JNIEnv *,Player *);

jstring getRealName (JNIEnv *, jobject);

void sendChat(JNIEnv *env, jobject thisObj, jstring jstr_message);

}
