/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bluebox_ll_Logger */

#ifndef _Included_bluebox_ll_Logger
#define _Included_bluebox_ll_Logger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bluebox_ll_Logger
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_Logger_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bluebox_ll_Logger
 * Method:    info
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_Logger_info
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bluebox_ll_Logger
 * Method:    error
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_Logger_error
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bluebox_ll_Logger
 * Method:    debug
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_Logger_debug
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bluebox_ll_Logger
 * Method:    warn
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_Logger_warn
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bluebox_ll_Logger
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_Logger_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
