/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bluebox_ll_entity_Player */

#ifndef _Included_bluebox_ll_entity_Player
#define _Included_bluebox_ll_entity_Player
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bluebox_ll_entity_Player
 * Method:    getRealName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bluebox_ll_entity_Player_getRealName
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_entity_Player
 * Method:    sendChat
 * Signature: (Ljava/lang/String;Lbluebox/ll/entity/Player/ChatType;)V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_entity_Player_sendChat
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
