/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bluebox_ll_gui_ModalForm */

#ifndef _Included_bluebox_ll_gui_ModalForm
#define _Included_bluebox_ll_gui_ModalForm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bluebox_ll_gui_ModalForm
 * Method:    sendTo
 * Signature: (Lbluebox/ll/world/entity/Player;Ljava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_gui_ModalForm_sendTo
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
