/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bluebox_ll_plugin_LeviLamina */

#ifndef _Included_bluebox_ll_plugin_LeviLamina
#define _Included_bluebox_ll_plugin_LeviLamina
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bluebox_ll_plugin_LeviLamina
 * Method:    hasPlugin
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_bluebox_ll_plugin_LeviLamina_hasPlugin
  (JNIEnv *, jclass, jstring);

/*
 * Class:     bluebox_ll_plugin_LeviLamina
 * Method:    getNativePlugin
 * Signature: (Ljava/lang/String;)Lbluebox/ll/plugin/Plugin;
 */
JNIEXPORT jobject JNICALL Java_bluebox_ll_plugin_LeviLamina_getNativePlugin
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
