/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bluebox_ll_world_block_BlockStack */

#ifndef _Included_bluebox_ll_world_block_BlockStack
#define _Included_bluebox_ll_world_block_BlockStack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bluebox_ll_world_block_BlockStack
 * Method:    get
 * Signature: (Lbluebox/ll/util/Location;)Lbluebox/ll/world/block/BlockStack;
 */
JNIEXPORT jobject JNICALL Java_bluebox_ll_world_block_BlockStack_get
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bluebox_ll_world_block_BlockStack
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bluebox_ll_world_block_BlockStack_getName
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_block_BlockStack
 * Method:    getId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bluebox_ll_world_block_BlockStack_getId
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_block_BlockStack
 * Method:    getType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bluebox_ll_world_block_BlockStack_getType
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_block_BlockStack
 * Method:    getLocation
 * Signature: ()Lbluebox/ll/util/Location;
 */
JNIEXPORT jobject JNICALL Java_bluebox_ll_world_block_BlockStack_getLocation
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_block_BlockStack
 * Method:    destroy
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bluebox_ll_world_block_BlockStack_destroy
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     bluebox_ll_world_block_BlockStack
 * Method:    getNBT
 * Signature: ()Lbluebox/ll/util/nbt/TagCompound;
 */
JNIEXPORT jobject JNICALL Java_bluebox_ll_world_block_BlockStack_getNBT
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_block_BlockStack
 * Method:    setNBT
 * Signature: (Lbluebox/ll/util/nbt/TagCompound;)V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_world_block_BlockStack_setNBT
  (JNIEnv *, jobject, jobject);

/*
 * Class:     bluebox_ll_world_block_BlockStack
 * Method:    cloneTo
 * Signature: (Lbluebox/ll/util/Location;)Lbluebox/ll/world/block/BlockStack;
 */
JNIEXPORT jobject JNICALL Java_bluebox_ll_world_block_BlockStack_cloneTo
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
