/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bluebox_ll_gui_ButtonForm */

#ifndef _Included_bluebox_ll_gui_ButtonForm
#define _Included_bluebox_ll_gui_ButtonForm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bluebox_ll_gui_ButtonForm
 * Method:    send
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/util/LinkedList;Ljava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_gui_ButtonForm_send
  (JNIEnv *, jclass, jlong, jstring, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
