/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bluebox_ll_world_container_Container */

#ifndef _Included_bluebox_ll_world_container_Container
#define _Included_bluebox_ll_world_container_Container
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bluebox_ll_world_container_Container
 * Method:    getType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bluebox_ll_world_container_Container_getType
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_container_Container
 * Method:    getSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bluebox_ll_world_container_Container_getSize
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_container_Container
 * Method:    isEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_bluebox_ll_world_container_Container_isEmpty
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_container_Container
 * Method:    addItem
 * Signature: (Lbluebox/ll/world/item/ItemStack;)V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_world_container_Container_addItem
  (JNIEnv *, jobject, jobject);

/*
 * Class:     bluebox_ll_world_container_Container
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_world_container_Container_clear
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_container_Container
 * Method:    getItem
 * Signature: (I)Lbluebox/ll/world/item/ItemStack;
 */
JNIEXPORT jobject JNICALL Java_bluebox_ll_world_container_Container_getItem
  (JNIEnv *, jobject, jint);

/*
 * Class:     bluebox_ll_world_container_Container
 * Method:    getAllItems
 * Signature: ()[Lbluebox/ll/world/item/ItemStack;
 */
JNIEXPORT jobjectArray JNICALL Java_bluebox_ll_world_container_Container_getAllItems
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_container_Container
 * Method:    setItem
 * Signature: (ILbluebox/ll/world/item/ItemStack;)V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_world_container_Container_setItem
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     bluebox_ll_world_container_Container
 * Method:    hasRoomFor
 * Signature: (Lbluebox/ll/world/item/ItemStack;)Z
 */
JNIEXPORT jboolean JNICALL Java_bluebox_ll_world_container_Container_hasRoomFor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     bluebox_ll_world_container_Container
 * Method:    addItemToFirstEmptySlot
 * Signature: (Lbluebox/ll/world/item/ItemStack;)Z
 */
JNIEXPORT jboolean JNICALL Java_bluebox_ll_world_container_Container_addItemToFirstEmptySlot
  (JNIEnv *, jobject, jobject);

/*
 * Class:     bluebox_ll_world_container_Container
 * Method:    removeItem
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_bluebox_ll_world_container_Container_removeItem
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
