/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bluebox_ll_util_nbt_TagCompound */

#ifndef _Included_bluebox_ll_util_nbt_TagCompound
#define _Included_bluebox_ll_util_nbt_TagCompound
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bluebox_ll_util_nbt_TagCompound
 * Method:    toBinary
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_bluebox_ll_util_nbt_TagCompound_toBinary
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_util_nbt_TagCompound
 * Method:    parse
 * Signature: ([B)Lbluebox/ll/util/nbt/TagCompound;
 */
JNIEXPORT jobject JNICALL Java_bluebox_ll_util_nbt_TagCompound_parse
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
