/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bluebox_ll_world_item_ItemStack */

#ifndef _Included_bluebox_ll_world_item_ItemStack
#define _Included_bluebox_ll_world_item_ItemStack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bluebox_ll_world_item_ItemStack
 * Method:    getCustomName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bluebox_ll_world_item_ItemStack_getCustomName
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_item_ItemStack
 * Method:    getRawName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bluebox_ll_world_item_ItemStack_getRawName
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_item_ItemStack
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bluebox_ll_world_item_ItemStack_getName
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_item_ItemStack
 * Method:    setCustomName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_world_item_ItemStack_setCustomName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bluebox_ll_world_item_ItemStack
 * Method:    getCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bluebox_ll_world_item_ItemStack_getCount
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_item_ItemStack
 * Method:    setCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_world_item_ItemStack_setCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     bluebox_ll_world_item_ItemStack
 * Method:    getTypeName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bluebox_ll_world_item_ItemStack_getTypeName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
