/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bluebox_ll_world_entity_Entity */

#ifndef _Included_bluebox_ll_world_entity_Entity
#define _Included_bluebox_ll_world_entity_Entity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bluebox_ll_world_entity_Entity
 * Method:    getType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bluebox_ll_world_entity_Entity_getType
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_entity_Entity
 * Method:    getUniqueId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_bluebox_ll_world_entity_Entity_getUniqueId
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_entity_Entity
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bluebox_ll_world_entity_Entity_getName
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_entity_Entity
 * Method:    getNameTag
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bluebox_ll_world_entity_Entity_getNameTag
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_entity_Entity
 * Method:    setNameTag
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_world_entity_Entity_setNameTag
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bluebox_ll_world_entity_Entity
 * Method:    getNbt
 * Signature: ()Lbluebox/ll/util/nbt/TagCompound;
 */
JNIEXPORT jobject JNICALL Java_bluebox_ll_world_entity_Entity_getNbt
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_entity_Entity
 * Method:    setNbt
 * Signature: (Lbluebox/ll/util/nbt/TagCompound;)V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_world_entity_Entity_setNbt
  (JNIEnv *, jobject, jobject);

/*
 * Class:     bluebox_ll_world_entity_Entity
 * Method:    getLocation
 * Signature: ()Lbluebox/ll/util/Location;
 */
JNIEXPORT jobject JNICALL Java_bluebox_ll_world_entity_Entity_getLocation
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_entity_Entity
 * Method:    kill
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_world_entity_Entity_kill
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_entity_Entity
 * Method:    getFeetLocation
 * Signature: ()Lbluebox/ll/util/Location;
 */
JNIEXPORT jobject JNICALL Java_bluebox_ll_world_entity_Entity_getFeetLocation
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_entity_Entity
 * Method:    getDimensionId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bluebox_ll_world_entity_Entity_getDimensionId
  (JNIEnv *, jobject);

/*
 * Class:     bluebox_ll_world_entity_Entity
 * Method:    teleport
 * Signature: (FFFIFF)V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_world_entity_Entity_teleport__FFFIFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint, jfloat, jfloat);

/*
 * Class:     bluebox_ll_world_entity_Entity
 * Method:    teleport
 * Signature: (FFFI)V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_world_entity_Entity_teleport__FFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint);

/*
 * Class:     bluebox_ll_world_entity_Entity
 * Method:    getEntities
 * Signature: ()[Lbluebox/ll/world/entity/Entity;
 */
JNIEXPORT jobjectArray JNICALL Java_bluebox_ll_world_entity_Entity_getEntities
  (JNIEnv *, jclass);

/*
 * Class:     bluebox_ll_world_entity_Entity
 * Method:    getEntity
 * Signature: (J)Lbluebox/ll/world/entity/Entity;
 */
JNIEXPORT jobject JNICALL Java_bluebox_ll_world_entity_Entity_getEntity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bluebox_ll_world_entity_Entity
 * Method:    spawn
 * Signature: (Ljava/lang/String;Lbluebox/ll/util/Location;)Lbluebox/ll/world/entity/Entity;
 */
JNIEXPORT jobject JNICALL Java_bluebox_ll_world_entity_Entity_spawn
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     bluebox_ll_world_entity_Entity
 * Method:    cloneTo
 * Signature: (Lbluebox/ll/util/Location;)Lbluebox/ll/world/entity/Entity;
 */
JNIEXPORT jobject JNICALL Java_bluebox_ll_world_entity_Entity_cloneTo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     bluebox_ll_world_entity_Entity
 * Method:    updateItems
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bluebox_ll_world_entity_Entity_updateItems
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
