#pragma once

/* DO NOT EDIT THIS FILE - it is machine generated */
#include "mc/world/actor/player/Player.h"
#include <jni.h>
/* Header for class bluebox_levilamina_engine_worlds_Player */

namespace lje::j_Player{
jobject newJavaPlayer(JNIEnv *,Player *);
/*
 * Class:     bluebox_levilamina_engine_worlds_Player
 * Method:    tell
 * Signature: (Ljava/lang/String;)V
 */
void tell
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bluebox_levilamina_engine_worlds_Player
 * Method:    getRealName
 * Signature: ()Ljava/lang/String;
 */
jstring getRealName
  (JNIEnv *, jobject);

}
